language: python
sudo: false

env:
  global:
  - KERAS_BACKEND=tensorflow
  - CUDA_VISIBLE_DEVICES=''
  #- PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
    - '3.6'

#creating conda environment:
before_install:
    #install miniconda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p "$PWD/miniconda/"
    - export PATH="$PWD/miniconda/bin/:$PATH"
    - yes|conda update conda>/dev/null

#install necessary packages
install:
    #pip install
    - pip install tensorflow
    - pip install keras
    #Source conda environment:
    - yes|conda env create -f speedcom_environment.yml>/dev/null
    - source activate speedcom

#only test on master and tests branches
branches:
    only:
    - master
    - tests

#lintr
before_script:
#    -"flake8 speedcom"
    - export KERAS_BACKEND=tensorflow
    - export CUDA_VISIBLE_DEVICES=''

#Run Unittests
script:
    - python numpyversion.py
    - which py.test
    - py.test --pyargs speedcom --cov-report term-missing --cov=speedcom --cov-config .coveragerc

#Print coverage reports
after_success:
    - coverage report
    - coveralls

#Annoy @jwa7
notifications:
    email: true
