language: python
sudo: false

#env:
  #global:
  #- PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
    - '3.6'

#creating conda environment:
before_install:
    #install miniconda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p "$PWD/miniconda/"
    - ls -lhtr
    - export PATH="$PWD/miniconda/bin/:$PATH"
    - echo $PATH
    - pwd
    #- conda update --yes conda

#pip install necessary packages
install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    #Source conda environment:
    - conda env create -f speedcom/speedcom_environment.yml
    - source activate speedcom_environment

    #Pip installs:
    #- pip install coverage
    #- pip install coveralls
    #- pip install flake8
    #- pip install pytest-cov
    #- pip install -r requirements.txt

#only test on master and tests branches
branches:
#  only:
    - master
    - tests

#lintr
#before_script:
#    -"flake8 speedcom"

#Run Unittests
script:
    - py.test --pyargs speedcom --cov-report term-missing --cov=speedcom
    #- coverage run -m unittest discover

#Print coverage reports
after_success:
    - coverage report
    - coveralls

#Annoy @jwa7
notifications:
    email: true
