language: python
sudo: false

env:
  global:
  - PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
- '3.6'

install:
#- pip install $PIP_DEPS
- pip install coverage
- pip install coveralls
- pip install flake8
- pip install pytest-cov
- pip install -r requirements.txt

#branches:
#  only:
- master
- testing
#before_script:
#  -"flake8 speedcom"
script:
  - py.test --pyargs speedcom --cov-report term-missing --cov=speedcom
  #- coverage run -m unittest discover
after_success:
  - coverage report
  - coveralls
notifications:
  email: true
